export const inventory = [
    {
        name: "cotton tshirt", 
        styleNumber: "MS13KT1906", 
        color: "blue", 
        src: "./images/cotton-blue.jpeg", 
        alt: "blue cotton tshirt", 
        size: ["S", "M", "L", "XL"], 
        price: 11, 
    }, {
        name: "cotton tshirt", 
        styleNumber: "MS13KT1906", 
        color: "black", 
        src: "./images/cotton-black.jpeg", 
        alt: "black cotton tshirt", 
        size: ["S", "M", "L", "XL"], 
        price: 11, 
    },{
        name: "cotton tshirt", 
        styleNumber: "MS13KT1906", 
        color: "white", 
        src: "./images/cotton-white.jpeg", 
        alt: "white cotton tshirt", 
        size: ["S", "M", "L", "XL"], 
        price: 11, 
    },{
        name: "print girls tee", 
        styleNumber: "MS13KT1907", 
        color: "blue", 
        src: "./images/print-blue.jpeg", 
        alt: "print girls tee blue", 
        size: ["S", "M", "L", "XL"], 
        price: 17, 
    }, {
        name: "print girls tee", 
        styleNumber: "MS13KT1907", 
        color: "red", 
        src: "./images/print-red.jpeg", 
        alt: "print girls tee red", 
        size: ["S", "M", "L", "XL"], 
        price: 17, 
    }, {
        name: "print girls tee", 
        styleNumber: "MS13KT1907", 
        color: "white", 
        src: "./images/print-white.jpeg", 
        alt: "print girls tee white", 
        size: ["S", "M", "L", "XL"], 
        price: 17, 
    }, {
        name: "flower pattern shirt", 
        styleNumber: "MS13KT1908", 
        color: "blue", 
        src: "./images/print-blue.jpeg", 
        alt: "flower pattern shirt blue", 
        size: ["S", "M", "L", "XL"], 
        price: 21, 
    },{
        name: "flower pattern shirt", 
        styleNumber: "MS13KT1908", 
        color: "red", 
        src: "./images/print-red.jpeg", 
        alt: "flower pattern shirt red", 
        size: ["S", "M", "L", "XL"], 
        price: 21, 
    },{
        name: "flower pattern shirt", 
        styleNumber: "MS13KT1908", 
        color: "white", 
        src: "./images/print-white.jpeg", 
        alt: "flower pattern shirt white", 
        size: ["S", "M", "L", "XL"], 
        price: 21, 
    }, {
        name: "check pattern shirt", 
        styleNumber: "MS13KT1910", 
        color: "blue", 
        src: "./images/check-blue.jpeg", 
        alt: "check pattern shirt blue", 
        size: ["S", "M", "L", "XL"], 
        price: 22, 
    }, {
        name: "check pattern shirt", 
        styleNumber: "MS13KT1910", 
        color: "gray", 
        src: "./images/check-gray.jpeg", 
        alt: "check pattern shirt gray", 
        size: ["S", "M", "L", "XL"], 
        price: 22, 
    }, {
        name: "check pattern shirt", 
        styleNumber: "MS13KT1910", 
        color: "red", 
        src: "./images/check-red.jpeg", 
        alt: "check pattern shirt red", 
        size: ["S", "M", "L", "XL"], 
        price: 22, 
    }]